# Tyler Banks
## Week 10 - 03/27/21
### Python NumPy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr1 = np.array((1,2,3,4,5,6))

In [7]:
arr1

array([1, 2, 3, 4, 5, 6])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
#0-D arrays
arr2 = np.array(50)

In [10]:
arr2

array(50)

In [11]:
print(arr2)

50


In [12]:
#1-D array
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [13]:
arr77 = np.array([1,7,3,7,'string'])
print(arr77)

['1' '7' '3' '7' 'string']


In [14]:
#2-D array - matrix

arr4 = np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(arr4)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [15]:
#3-D array

arr66 = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(arr66)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
arr5 = np.array([[[1,4,7],[2,5,8]],[[3,6,9],[10,20,30]]])
print(arr5)

[[[ 1  4  7]
  [ 2  5  8]]

 [[ 3  6  9]
  [10 20 30]]]


In [17]:
print(arr2.ndim)

0


In [18]:
print(arr3.ndim)

1


In [19]:
print(arr4.ndim)

2


In [20]:
print(arr5.ndim)

3


In [21]:
#array indexing
print(arr3)

[1 2 3 4 5 6]


In [22]:
print(arr3[1])

2


In [23]:
print(arr3[-1])

6


In [24]:
print(arr3[0] + arr3[3])

5


In [25]:
#access 2-D array
print(arr4)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [26]:
print(arr4[0,1])

3


In [27]:
print(arr4[-1,1])

4


In [28]:
print(arr4[1,-1])

10


In [29]:
print(arr4[1,3])

8


In [30]:
print(arr5)

[[[ 1  4  7]
  [ 2  5  8]]

 [[ 3  6  9]
  [10 20 30]]]


In [31]:
print(arr5[0,1,1])

5


In [32]:
print(arr5[1,1,2])

30


In [33]:
marr = np.array([1,2,3,4,5], ndmin=5)

In [34]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [35]:
marr.ndim

5

In [36]:
print(arr4)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [37]:
print(arr4[0,-1])

9


In [38]:
#alicing np arrays
#[start:end]
#{start:end:step}
#[:end] start is 0
#[start:] end will be the length of the array

In [39]:
print(arr3[3])

4


In [40]:
print(arr3[1:4])

[2 3 4]


In [41]:
arr3

array([1, 2, 3, 4, 5, 6])

In [42]:
print(arr3[3:])

[4 5 6]


In [43]:
#slice elements from the beginning index to index 3 (not included)
print(arr3[3:])

[4 5 6]


In [44]:
print(arr3)

[1 2 3 4 5 6]


In [45]:
#slice from index 3 to end index 1 from the end of the array
print(arr3[-3:-1])

[4 5]


In [46]:
print(arr3[1:5:2])

[2 4]


In [47]:
print(arr3)

[1 2 3 4 5 6]


In [48]:
print(arr3[1:5:3])

[2 5]


In [49]:
#return every other element in the entire array
print(arr3[::])

[1 2 3 4 5 6]


In [50]:
print(arr3[::2])

[1 3 5]


In [51]:
#slicing 2-D  

In [52]:
print(arr4[:,3])

[7 8]


In [53]:
print(arr4[:,1:3])

[[3 5]
 [4 6]]
