# Tyler Banks
## Week 11 - 04/03/21
### Python NumPy Universal Functions

In [3]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [10]:
#zip

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Roberts")

fullname = zip(fname,lname)
print(tuple(fullname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Roberts'))


In [12]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [17]:
import numpy as np 

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [20]:
arr1 = np.random.randn(10)
arr1

array([-0.33539665, -0.35270846, -1.38360718,  0.10972771,  0.49239354,
       -0.31563942,  0.21710442,  1.16362488,  0.033178  ,  0.37228403])

## 

In [21]:
arr2 = np.random.randn(10)

arr2

array([ 0.67609712, -0.49572051,  1.36636603,  1.2168082 , -0.10979481,
       -0.33451937, -1.173104  , -0.94656237, -0.1506751 , -1.86079361])

In [22]:
np.add(arr1,arr2)

array([ 0.34070047, -0.84842897, -0.01724115,  1.3265359 ,  0.38259873,
       -0.65015879, -0.95599958,  0.21706251, -0.11749711, -1.48850958])

In [23]:
np.maximum(arr1,arr2)

array([ 0.67609712, -0.35270846,  1.36636603,  1.2168082 ,  0.49239354,
       -0.31563942,  0.21710442,  1.16362488,  0.033178  ,  0.37228403])

In [24]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [26]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [33]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False, True, True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [34]:
arr3 = [r1 if c else r2 for r1,r2, c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [35]:
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

# Tyler Banks
## Week 12 - 04/10/21
### Python NumPy Universal Functions

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False], [True, True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [4]:
np.where([[True,False],[True,True]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [6]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.12568354, -0.0229374 , -0.3446534 ],
       [ 1.8724118 , -0.45076329, -1.32028282],
       [ 1.15629741, -0.72451582, -1.03173384]])

In [8]:
np.where(arr<0, 0,arr)

array([[0.        , 0.        , 0.        ],
       [1.8724118 , 0.        , 0.        ],
       [1.15629741, 0.        , 0.        ]])

In [9]:
arr_b = np.array([True,False,True,False,False])

arr_b.any()

True

In [11]:
arr_b.all()

False

In [12]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [13]:
np.in1d(['Apple','Cherry','Grape'], fruits)

array([ True,  True, False])

In [14]:
#Statistical Measures
arr = np.array([[1,2,3,],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr)


(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr.sum()

45

In [17]:
arr.sum(0)

array([12, 15, 18])

In [18]:
arr.sum(1)

array([ 6, 15, 24])

In [19]:
print(arr)
np.sum(arr, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [20]:
print(arr)
np.sum(arr, axis = None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [22]:
arr.mean()

5.0

In [23]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [24]:
np.mean(arr, axis = 0)

array([4., 5., 6.])

In [25]:
np.mean(arr, axis = 1)

array([2., 5., 8.])

In [27]:
np.mean(arr, axis = None)

5.0

In [28]:
arr.var()

6.666666666666667

In [32]:
arr.std()

2.581988897471611

In [33]:
arr = np.array([3,6,8,9,4,5,3,6,2,3,4,6,5,1,9,11,19,18])

arr.sort()

arr

array([ 1,  2,  3,  3,  3,  4,  4,  5,  5,  6,  6,  6,  8,  9,  9, 11, 18,
       19])

In [34]:
print(arr)

[ 1  2  3  3  3  4  4  5  5  6  6  6  8  9  9 11 18 19]


In [36]:
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a = np.arange(25).reshape((5,5))

In [39]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
a*i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [42]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)

a*i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [43]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [44]:
m*i

matrix([[1., 2.],
        [3., 4.]])

In [46]:
#Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print('------------------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
------------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [47]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [50]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [51]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [57]:
arr_3d.transpose((2,1,0))

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [58]:
np.random.random((4,4))

array([[0.34157036, 0.11078353, 0.13364724, 0.57886124],
       [0.66219448, 0.98439748, 0.32992742, 0.95171561],
       [0.30765944, 0.07775485, 0.14849185, 0.71322315],
       [0.85033145, 0.72539572, 0.44052416, 0.69280413]])

In [59]:
from numpy.random import random
random((4,4))

array([[0.22374595, 0.8436815 , 0.42850469, 0.14665728],
       [0.33194143, 0.78258992, 0.56999023, 0.1096848 ],
       [0.83036   , 0.37798874, 0.30493635, 0.04430092],
       [0.26215585, 0.13549535, 0.56707738, 0.33600725]])

In [62]:
from numpy.random import randn

randn(5)

array([ 0.95866428,  1.2582206 ,  0.28997439,  0.17786601, -0.02124188])

In [63]:
np.random.randint(10,50)

27

In [64]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

In [65]:
website

'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'

In [66]:
import webbrowser
webbrowser.open(website)

True

In [67]:
import pandas as pd