# Tyler Banks
## Week 10 - 03/27/21
### Python NumPy Array Processes

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [4]:
print(my_arr.dtype)

int32


In [5]:
fruits = ['orange','apple','cherry','grape']

my_strArr = np.array(fruits)

In [6]:
print(my_strArr.dtype)

<U6


In [7]:
my_arr2 = np.array([11,22,33,44,55], dtype='S')

In [8]:
print(my_arr2.dtype)

|S2


In [9]:
my_arr2 = np.array([1,2,3,4,5], dtype='S')

print(my_arr2.dtype)

|S1


In [12]:
my_arr3 = np.array([5,6,7,8,9], dtype ='i4')

In [13]:
print(my_arr3.dtype)

int32


In [14]:
my_errArr = np.array(['1','2','3','4','5'], dtype = 'i')

In [15]:
print(my_arr)

[11 22 33 44 55 66 77]


In [16]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)

In [17]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [21]:
arr = np.array([1,0,0,4,5,2,7,5])

In [22]:
print(arr.dtype)

int32


In [23]:
bool_arr = arr.astype(bool)

In [24]:
print(arr)
print(bool_arr)

[1 0 0 4 5 2 7 5]
[ True False False  True  True  True  True  True]


In [25]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

In [26]:
my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [34]:
#numpy built-in functions to generate arrays from existing arrays
#copy and view, instead of using = 

my_lst = [11,12,13,14,15]

arr = np.array(my_list)

c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [35]:
print(c_arr)

[11 12 13 14 15]


In [36]:
#view
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [37]:
arr[3] = 4

print(arr)
print(c_arr)


[11 12 13  4 15]
[11 12 13 14 15]


In [39]:
#view
c_arr[2] = 3
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12  3 14 15]


In [40]:
print(c_arr.base)

None


In [41]:
#shape gives the number elements in each dimension

In [42]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
print(my_arr.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2
(2, 5)


In [43]:
#return 2 dimensions and each dimension has 5 elements 

In [45]:
arr = np.array(lst1, ndmin = 4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [46]:
# each index in the shape tells the number of elements in each dimension